### ISSUE TITLE
/usr/local/apache2/bin/httpd not found or not executable

### ISSUE THREAD

**Issue by 13820657629** [0xbigshaq/apache-afl#1]

**Comment by 13820657629** [comment]
when I run ./afl-runner.sh, it showed an error: /usr/local/apache2/bin/httpd not found or executable. How can I slolve this problem? show I add command --prefix=/usr/local/apache2 in afl-toolchain.sh after ./configure?

**Comment by 0xbigshaq** [comment]
Hi @13820657629 , sorry for the delayed reply, took me awhile to notice it.

Regarding your issue:
I assume it's because the `./afl-toolchain.sh` script responsible for building the _httpd_ binary, not installing it. 

After running the script, you should have a `httpd-2.4.52/` directory with all the compiled stuff.

Run:
```
cd httpd-2.4.52/
make install
cd ../fuzzer-dir/
./afl-runner.sh
```

The `install` Makefile target will copy it to where it should be so the runner can find the binary. [That's probably the root cause](https://github.com/0xbigshaq/apache-afl/blob/main/afl-toolchain.sh#L96) for your issue(I did this for a reason, but it's been over a year now so I don't remember why). I'll add a clarification in the _README.md_ file(or, uncomment that line in the bash script) soon.

**Comment by ubdussamad** [comment]
Hello, I noticed that you're only compiling httpd using AFl and not the other libraries, is there a reason for that? Most folks compile everything with AFL.

 Also, I'm not sure why yet, but the `make install` (for httpd) fails if we run this code in afl_plus_plus image. If we run it on a normal ubuntu image then the `make install` succeeds but now the fuzzer cannot find any new paths. (I left it running for a while and no new paths were found.)
